version: '3.8'

services:
  restic-rest:
    container_name: restic-rest
    image: restic/rest-server:0.12.0
    environment:
      OPTIONS: "--prometheus"
    ports:
      - 127.0.0.1:8000:8000
    restart: unless-stopped
    volumes:
      - restic-rest-backup:/data

volumes:
  restic-rest-backup: